### ISSUE TITLE
getInitialProps to component props

### ISSUE THREAD

**Issue by rayandrew** [alidcastano/rogue.js#37]
Is there any way to passing value of getInitialProps to suitable component props like Next.js or After.js?

Thank you!

**Comment by alidcastano** [comment]
You mean like passing each component/page its `getInitialProps`?

I considered this in #6. One drawback of only having an `App.js` instead of a `/pages` directory that we can scan is that we don't have access to pages independently unless we try to recreate your component tree or wrap React Router's components.

But honestly, this is only a problem if your using Rogue with REST and need to fetch data per page. But with Grapqhl, each componen queries data it needs so receiving props per page is not necassary; so using `getInitialProps` is primarily for configuring SSR providers, handling page redirects, etc.

**Comment by rayandrews** [comment]
Ah gotcha, that's the intended behavior and drawback. It's kinda sad not having that feature but it's okay as long as we have another solution like using redux or apollo.

Can I ask more questions? 

Why it seems that examples with razzle and rogue cli have different behavior?

With rouge cli :
![rouge1](https://user-images.githubusercontent.com/4437323/42427361-5bc18dda-8358-11e8-9ab4-9e97ccfb9dc5.gif)

With razzle :
![rouge2](https://user-images.githubusercontent.com/4437323/42427378-6dc28fc0-8358-11e8-88df-16f8bdcf4c6a.gif)


SSR_DATA in rouge cli is updated when route component has getInitialProps, but not in razzle.

Is this intended?

Thank you

**Comment by rayandrews** [comment]
> Btw, if necessary you can always pass props from the App.js component to each respective page; you can namespace the props to make that easier too

that's the possible solution I think.

hahaha, okay, will push the repo to reproduce the issue, by the way I will open PR to fix some typo.

Thank you @alidcastano!
