### ISSUE TITLE
Different behavior of Rogue

### ISSUE THREAD

**Issue by rayandrews** [alidcastano/rogue.js#39]
Referring our discussions in this issue #37 

With rouge cli :
![rouge1](https://user-images.githubusercontent.com/4437323/42427361-5bc18dda-8358-11e8-9ab4-9e97ccfb9dc5.gif)

With razzle :
![rouge2](https://user-images.githubusercontent.com/4437323/42427378-6dc28fc0-8358-11e8-88df-16f8bdcf4c6a.gif)

Github repo to reproduce:

https://github.com/rayandrews/reproduce-rogue-behavior

what's the different?
1. SSR_DATA not reloaded in razzle example
2. Blink link redirect (because of getInitialProps) in rouge-cli (the perks: SSR_DATA updated nicely)

cc: @alidcastano

**Comment by alidcastano** [comment]
0.4.0 are first releases of packages; if you update `roguejs/cli` in hello-world then both of them encounter same error

the initial difference was that client bundle wasn't being served correctly in previous version of `roguejs/cli`

but that still doesn't answer client-server mistach with router; gotta look into that

**Comment by alidcastano** [comment]
Did you get this example from Razzle site?

**Comment by alidcastano** [comment]
Hmm okay so one property that is mismatched is `history.length`. 

Reading up on it here https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/api/history.md 

and here https://github.com/ReactTraining/history/issues/582

> history.length is the number of locations in the joint session history, not the current site's session history. 

in other words, it seems to be a browser only property, hence why it only appears in client (which has BrowserRouter) and not server (which has StaticRouter)

If you selectively render props (e.g. `props.location` instead of all `props`) error disappears

**Comment by rayandrews** [comment]
> Did you get this example from Razzle site?

No, I create it to test Rogue in another build system

> If you selectively render props (e.g. props.location instead of all props) error disappears

Ah get it, Will you release fix on this?

How about the SSR_Data? It seems not loaded properly on Razzle? or is it intended?

**Comment by alidcastano** [comment]
Unless we're configuring the router wrong (which idt we are) there's nothing to do on our side (I'm sure you'd get the same error if you try to render all router props in Afterjs)

by incorrect SSR_DATA you mean what you returned from `getIntialProps`? I see the `{ stuff: 'more stuffs' }` does show up correctly.

Remember that as of now, if you'd like to access this data in your nested components you need to pass it from your root component

**Comment by alidcastano** [comment]
I'm starting to think that the `getInitialProps` name isn't ideal, since it indicates that data is being passed to each respective component

Obviously that would be ideal, but just not sure if it's worth the hassle. In order to do that we'd need to wrap the Router components

I'll be giving it some though but if you'd like to make request for this, open a new issue and have examples of where'd it'd be necessary even if using Apollo Graphql to query data
