### ISSUE TITLE
Rogue community?

### ISSUE THREAD

**Issue by IniZio** [alidcastano/rogue.js#76]
This library really excels in routing compared to other SSR solutions, and I think it deserves more attention such as a public chatroom or promotion posts, any thoughts?

**Comment by alidcastano** [comment]
Hey IniZio, thanks for taking interest in the project.

I do believe the Rogue App is the most elegant solution to building ssr apps in React. It takes advantage of existing community tools (React Router, React Helmet) an lets you compose your app however you like. Best part, since Rogue is just a tiny wrapper gluing the best ssr tools for React, there's less surface area for bugs/issue, and as such, Rogue App doesn't depend on a community as much as other frameworks.

That being said, I do agree that it's nice to see people rallying around a given framework or tool. But I unfortunately don't have the time to promote Rogue atm. I'm focused on a web app I'm building (the app from which Rogue logic was extracted out of). I plan to improve Rogue along the way, but haven't had any pressing issues yet.

Happy to facilitate any community development / promotional posts, etc. But as described above, I don't have the the time to take it on myself atm.
