### ISSUE TITLE
rogue-cli support plans

### ISSUE THREAD

**Issue by Kanuny** [alidcastano/rogue.js#77]
Hi. I didn't follow roguejs project couple of months until today. And today I found that there is no rogue-cli anymore :(. Is there any plans to bring it back in future? And what was the reason of removing it?

**Comment by alidcastano** [comment]
the original reason for creating rouge cli was to have the dev/build experience run on parcel rather than webpack, but I ran into some issues a few months back when attempting it and just never ended up having time to go back to it, so I figured it was better to deprecate it than to half-ass it or leave it unfinished

plus, solutions like razzle are already production ready and easy to setup. 

a single `App.js` entry point and zero config dev experience would be nice to have, but given my current time constraints, much better to delegate to other libraries that will ensure the job gets done right even if it means a little extra boilerplate

**Comment by alidcastano** [comment]
good news, i ran into some issues with webpack and gave parcel another try

roguejs/cli is back up and running :) this time it looks to finally running smoothly (had several issues before with Parcel and ssr). will make release later today
